baseURL = "http://beta.klar.no"

title = "Mysite"
DefaultContentLanguage = "no"
languageName = "No"
languageCode = "no"
publishDir = "docs"


[params]
logo = "/images/logo.svg"



[languages]
  [languages.no]
     languageName = "No"
     languageCode = "no"
     weight = "1"
     thumbnail = ""
     title = "Home"
     description = "Hjemmeside"

 [[languages.no.menu.meny]]
  

 [[languages.no.menu.meny]]
     name = "about"
     identifier = "about"
     description = ""
     title = "About"
     url = "/about/"
     weight = "1"

 [[languages.no.contact.meny]]
     name = "contact"
     identifier = "contact" 
     description = ""
     title = "Contact us"
     url = "/contact/"
     weight = "2"    


